export interface NaurtPoint {
  latitude: number,
  longitude: number,
  timestamp: String,
  locationProviderTimestamp: String,
  horizontalAccuracy: number,
  speed: number,
  heading: number,
  speedAccuracy: number,
  headingAccuracy: number,
  horizontalCovariance: number,
  altitude: number,
  verticalAccuracy: number,
  cumulativeDistance: number,
  motionFlag: String,
  locationOrigin: String,
  environmentFlag: String,
  backgroundStatus: String,
}